version: '3.9'
services:
  web:
    build: .
    container_name: django_web
    env_file:
      - .env
    command: bash -lc "python manage.py migrate && gunicorn project4.wsgi:application -b 0.0.0.0:8000 --workers 3 --config gunicorn.conf.py"
    volumes:
      - .:/code
    expose:
      - "8000"
  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./static:/code/static
    depends_on:
      - web
